name: Build Android Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Build Binary
      run: |
        # 1. Setup Compiler
        export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
        export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
        
        # 2. Environment Wajib
        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64
        
        # 3. FIX WAJIB: Paksa char menjadi signed (agar Go tidak error int8)
        # Kita HAPUS CGO_LDFLAGS dari sini agar tidak menimpa settingan library
        export CGO_CFLAGS="-fsigned-char"
        export CGO_CXXFLAGS="-fsigned-char -std=c++17 -w"
        
        # 4. Download Library Terbaru
        go get github.com/AllenDang/cimgui-go@main
        go mod tidy
        
        # 5. BUILD COMMAND (THE REAL FIX)
        # -tags "static" : Paksa compile source C++
        # -extldflags : Tambahkan library android tanpa menghapus library internal ImGui
        go build -tags "static" -v -ldflags "-s -w -extldflags '-landroid -llog'" -o aplikasiku

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasil-build-android
        path: aplikasiku

