name: Build Android Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Build Binary
      run: |
        # Setup Compiler
        export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
        export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
        
        # Settingan Go
        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64
        
        # --- PERBAIKAN UTAMA ADA DI SINI ---
        # Memaksa char menjadi signed agar cocok dengan Go wrapper
        export CGO_CFLAGS="-fsigned-char"
        # -----------------------------------
        
        # Download library
        go mod tidy
        
        # Build
        go build -v -ldflags "-s -w" -o aplikasiku

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasil-build-android
        path: aplikasiku

