name: Build Android Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Build Binary
      run: |
        # 1. Setup Compiler (Jembatan ke Android)
        export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
        export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
        
        # 2. Aktifkan CGO
        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64
        
        # 3. FIX COMPILER (Masalah char/int8 yang tadi)
        export CGO_CFLAGS="-fsigned-char"
        
        # 4. FIX LINKER (Masalah baru Anda: C++ Library)
        # Kita wajib menyertakan -lstdc++ (Library C++) dan -lm (Matematika)
        export CGO_LDFLAGS="-static-libstdc++ -lm -latomic -llog -landroid"
        
        # 5. Download & Build
        go mod tidy
        go build -v -ldflags "-s -w" -o aplikasiku

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasil-build-android
        path: aplikasiku

