name: Build TUI Mod Menu

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build ELF Binary
      run: |
        # Setup Environment untuk Cross-Compile ke Android ARM64
        # KITA MATIKAN CGO (CGO_ENABLED=0) agar jadi binary murni yang portabel
        export CGO_ENABLED=0
        export GOOS=android
        export GOARCH=arm64
        
        # Download dependencies
        go mod tidy
        
        # Build Command
        # -s -w untuk memperkecil ukuran file
        # Output file bernama 'modmenu'
        go build -ldflags "-s -w" -o modmenu

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-modmenu-termux
        path: modmenu

