name: Build Android Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Build Binary
      run: |
        # 1. Setup Compiler
        export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
        export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
        
        # 2. Environment Dasar
        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64
        
        # 3. FIX CRITICAL: Paksa char signed (masalah int8) & Standar C++
        export CGO_CFLAGS="-fsigned-char"
        export CGO_CXXFLAGS="-fsigned-char -std=c++11"
        
        # 4. LINKER SIMPLE: Biarkan NDK mengatur C++, kita cukup minta log & android
        # Menghapus '-static-libstdc++' yang tadi bikin error undefined symbol
        export CGO_LDFLAGS="-landroid -llog"
        
        # 5. Download Library
        go mod tidy
        
        # 6. BUILD COMMAND (THE FIX)
        # Menambahkan -tags "static" adalah kunci agar kode C++ ImGui ikut dikompilasi
        go build -tags "static" -v -ldflags "-s -w" -o aplikasiku

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasil-build-android
        path: aplikasiku

