name: Build Android Binary

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' # Kita naikkan versi Go biar lebih aman

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        add-to-path: true

    - name: Build Binary
      run: |
        # 1. Setup Compiler
        export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
        export CXX=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang++
        
        # 2. Environment Dasar
        export CGO_ENABLED=1
        export GOOS=android
        export GOARCH=arm64
        
        # 3. FIX Flags (Penting!)
        # -fsigned-char: Agar char Android sama dengan Go
        # -std=c++17: Agar fitur modern C++ ImGui jalan
        export CGO_CFLAGS="-fsigned-char"
        export CGO_CXXFLAGS="-fsigned-char -std=c++17 -w" 
        
        # 4. Linker Sederhana
        export CGO_LDFLAGS="-landroid -llog"
        
        # 5. Download Library (Pastikan versi @main terambil)
        go get github.com/AllenDang/cimgui-go@main
        go mod tidy
        
        # 6. Build Command
        # Kita hapus tags "static" karena versi main biasanya sudah auto-detect
        go build -v -ldflags "-s -w" -o aplikasiku

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hasil-build-android
        path: aplikasiku

